# Generated by Django 3.2.6 on 2021-08-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='', max_length=50)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('mtext', models.JSONField(blank=True, max_length=255, null=True)),
                ('mdt', models.DateTimeField(auto_now=True)),
                ('height', models.FloatField(blank=True, default=0.0, max_length=255)),
                ('weight', models.FloatField(blank=True, default=0.0, max_length=255)),
                ('age', models.IntegerField(default=0)),
                ('sex', models.IntegerField(default=0)),
            ],
        ),
    ]
